# Generated by Django 4.1.7 on 2023-03-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_name', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('place_of_events', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
